service: ecs-circuit-breaker

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-west-1
  ecr:
    scanOnPush: true
    images:
      test_ecs_circuit_breaker:
        path: .
  iamRoleStatements:
    - Effect: Allow
      Action:
        - ecr:DescribeRepositories
      Resource: '*'

resources:
  Resources:
    MyEcsCircuitBreaker:
      Type: AWS::ECS::Service
      Properties:
        Cluster: ecs-circuit-breaker-fargate
        DeploymentConfiguration:
          DeploymentCircuitBreaker:
            Enable: true
            Rollback: true
        TaskDefinition: your-task-definition-arn
        LaunchType: FARGATE
        NetworkConfiguration:
          AwsvpcConfiguration:
            Subnets:
              - subnet-02dff2d9fe3c90149
              - subnet-0c439dfbd6adce641
            SecurityGroups:
              - sg-0005ab2058648df29
        DesiredCount: 1
        PropagateTags: SERVICE

fargate:
  clusterName: ecs-circuit-breaker-fargate
  containerInsights: false
  memory: '0.5GB'
  cpu: 256
  environment:
    name: test
  vpc:
    assignPublicIp: false
    securityGroupIds:
      - sg-0005ab2058648df29
    subnetIds: 
      - subnet-02dff2d9fe3c90149
      - subnet-0c439dfbd6adce641
  

plugins:
  - serverless-fargate